---
- hosts: honeypots
  remote_user: root
  tasks:
    - name: Install firewalld on remote server
      package:
        name: firewalld
        state: present

    - name: Install python3 on remote server
      package:
        name: python3
        state: present

    - name: Make sure that the firewalld is running
      systemd:
        name: firewalld
        state: started
        enabled: yes

    - name: Compress directory honeypot into honeypot.tar.gz
      archive:
        path: ../../honeypot
        dest: /tmp/honeypot.tgz
      delegate_to: localhost

    - name: Copy honeypot.tar.gz to remote server
      copy:
        src: /tmp/honeypot.tgz
        dest: /root/honeypot.tgz
        owner: root
        group: root

    - name: Extract honeypot on the remote server
      unarchive:
        src: /root/honeypot.tgz
        dest: /root/
        remote_src: yes

    - name: Update pip
      command: python3 -m pip install --upgrade pip

    - name: Install pip dependencies
      pip:
        name: paramiko

    - name: Create /var/log/python-honeypot dir for logs
      file:
        path: /var/log/python-honeypot
        state: directory
        mode: '0600'

    - name: Check that the somefile.conf exists
      stat:
        path: /root/.ssh/honeypot.key
      register: stat_result

    - name: Create fake SSH keys
      command: ssh-keygen -t rsa -f /root/.ssh/honeypot.key -N ""
      when: not stat_result.stat.exists

    - name: Create fake SSL cert and key
      command: openssl req -x509 -nodes -subj '/CN=localhost'  -newkey rsa:4096 -keyout /etc/pki/tls/private/key.pem -out /etc/pki/tls/certs/cert.pem -days 365

    - name: Copy python-honeypot.service to systemd
      copy:
        src: /root/honeypot/python-honeypot.service
        dest: /lib/systemd/system
        remote_src: yes

    - name: Add 6000 to firewall
      command: firewall-cmd --permanent --add-port=6000/tcp

    - name: Reload firewalld
      command: firewall-cmd --reload

    - name: Insert a line at the end of a file.
      lineinfile:
        path: /etc/ssh/sshd_config
        line: Port 6000

    - name: Insert a line at the end of a file.
      lineinfile:
        path: /etc/ssh/sshd_config
        line: PasswordAuthentication no
        regexp: 'PasswordAuthentication yes'

    - name: Restart sshd
      systemd:
        name: sshd
        state: restarted

    - name: Rebuild of rpm db (needed after ssh port swtich)
      command: rpm --rebuilddb

    - name: Enable python-honeypot.service and start the honeypot
      systemd:
        name: python-honeypot.service
        state: started
        enabled: yes

    - name: Start cronjob for gathering facts
      cron:
          name: "a job for reboot"
          special_time: reboot
          job: "/some/job.sh"
